# Generated by Django 6.0.4 on 2026-05-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Invoice Template', max_length=100)),
                ('company_name', models.CharField(default='Pravin Enterprises', max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('company_phone', models.CharField(blank=True, max_length=30)),
                ('company_email', models.EmailField(blank=True, default='pravin@enterprises.com', max_length=254)),
                ('title', models.CharField(default='Tax Invoice', max_length=100)),
                ('footer_message', models.TextField(default='Thank you for your purchase!')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoice_templates',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
