# Generated by Django 6.0.4 on 2026-05-05 13:04

from django.db import migrations


def create_default_invoice_template(apps, schema_editor):
    InvoiceTemplate = apps.get_model('payments', 'InvoiceTemplate')
    InvoiceTemplate.objects.get_or_create(
        name='Default Invoice Template',
        defaults={
            'company_name': 'Pravin Enterprises',
            'company_email': 'pravin@enterprises.com',
            'title': 'Tax Invoice',
            'footer_message': 'Thank you for your purchase!',
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoicetemplate'),
    ]

    operations = [
        migrations.RunPython(create_default_invoice_template, migrations.RunPython.noop),
    ]
