# Generated by Django 5.2 on 2026-03-04 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(help_text='Name of your hardware shop', max_length=255)),
                ('gst_number', models.CharField(help_text='GST Registration Number (15 digits)', max_length=15, unique=True)),
                ('email', models.EmailField(help_text='Office/Shop email address', max_length=254)),
                ('phone_number', models.CharField(help_text='Shop contact number', max_length=17)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp business number (optional)', max_length=17)),
                ('shop_address', models.TextField(help_text='Complete shop/office address')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name for invoices', max_length=100)),
                ('bank_account', models.CharField(blank=True, help_text='Bank account number', max_length=20)),
                ('ifsc_code', models.CharField(blank=True, help_text='IFSC code', max_length=11)),
                ('registration_number', models.CharField(blank=True, help_text='Business registration number', max_length=50)),
                ('pan_number', models.CharField(blank=True, help_text='PAN number (10 digits)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Profile',
                'verbose_name_plural': 'Shop Profiles',
                'db_table': 'shop_profiles',
            },
        ),
    ]
